package demo.domain;

import java.time.Instant;
import java.util.UUID;

import org.socialsignin.spring.data.dynamodb.marshaller.Instant2EpocheDynamoDBMarshaller;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "USER")
public class User {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey()
	private UUID id;

	@DynamoDBAttribute
	private String firstname;

	@DynamoDBAttribute
	private String lastname;

	@DynamoDBTypeConverted(converter = Instant2EpocheDynamoDBMarshaller.class)
	private Instant birthday;

	@DynamoDBAttribute
	private long age;
}
